### ISSUE TITLE
Задача 5: дополнительные опции, влияющие на стоимость

### ISSUE THREAD

**Issue by DarkCat09** [IngCenter/ADoors#9]
У нас в панельке с опциями есть ещё несколько характеристик: ширина полотна, наличие наличника (масло масляное) и ручки...  
Такое чувство, будто в issue #2 их обидели :slightly_smiling_face: 

Требуется в функцию [`ComputeCost(int count = 1)`](https://github.com/IngCenter/ADoors/blob/main/ADoors/Door.cs#L81), которая и считает стоимость двери/дверей, использовать ширину полотна.

Как вычислять? Фантазируйте!  
Однако, важно, чтобы стоимость не была запредельной (например, прибавляешь 100 мм в WidthChoice, а тебе +1 млн руб. к дверке :slightly_smiling_face: )

Предлагаю использовать следующее выражение: `Width - 400`. Надеюсь, понимаете, что я вычитаю 400, так как это минимальный вариант, а в стоимость двери уже должно входить хоть какое-то полотно... (Прекрасно объясняю...)  
Решил вычислять именно так, потому что в калькуляторе, при выборе полотна на 900 мм, прибавляется 820руб., а это почти равно той самой ширине.

Ещё не знаю, кому дать эту задачу. Если кто хочет - берите, только сначала сообщите. Может, я сделаю.

**ОТПРАВЛЯТЬ в ветку `task5`**

**Comment by mabramovsd** [comment]
Ну так-то [здесь](https://docs.google.com/document/d/1DVkudVb_S11II8YGHELQv1AV_7k4jgRH2opX1_-cGCY/edit) сказано про влияние ширины, руки и прочего на стоимость. Ручка стоит 1200, каждые 10 сантиметров ширины полотна добавляют 20% к стоимости

Это я к тому, что вместо "фантазируйте" можно было сказать "берите формулы отсюда")

**Comment by DarkCat09** [comment]
@mabramovsd, спасибо, я не особо внимательно читал требования.  
Значит, не фантазировать, а сделать по документу)  
Вот Вы и сделаете)
